version: "3"
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=books
    volumes:
      - "pgsql_data:/var/lib/postgresql/data"
      - ./database/schema.sql:/docker-entrypoint-initdb.d/db.sql
    networks:
      - test-r2dbc-network
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8083:80"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - PGADMIN_DEFAULT_EMAIL=user@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=useruser
    networks:
      - test-r2dbc-network
    depends_on:
      - db
  app:
    image: test-r2dbc-img:latest
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_NAME: books
      DB_USERNAME: root
      DB_PASSWORD: root
    networks:
      - test-r2dbc-network
    depends_on:
      - db
      - pgadmin
    restart: on-failure:100

volumes:
  pgsql_data:
networks:
  test-r2dbc-network:
    driver: bridge
